img_api/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'img_api'

urlpatterns = [
    # path('',views.home,name="home"),
    path('', views.generateView,name='image-generate'),
    path('gallery/',views.galleryView ,name='image-gallery'),
    path('image/<int:id>', views.detailView,name='image-detail'),
    # path('media/images/<int:id>', views.detailView,name='image-detail'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


img_gen/urls.py

from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('img_api.urls')),
]

img_api/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class GeneratedImage(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    text = models.CharField(max_length=250, blank=True, null=True)
    image = models.ImageField(upload_to="images")
    # json_response = models.JSONField(("api_json"),blank=True,null=True)
    img_bytes = models.BinaryField(verbose_name="Img Binary", blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    # image_url = models.URLField(unique=True)#firebase url
    def get_absolute_url(self):
        return reverse("img_api:image-detail", kwargs={"id": self.id})

img_api/views.py
import base64
from django.shortcuts import get_object_or_404, render, HttpResponse
import requests,json,os
from .models import GeneratedImage
from django.core.paginator import Paginator
from django.core.files.base import ContentFile
from django.core.files.storage import default_storage


def galleryView(request):
    try:
        generated_images = GeneratedImage.objects.all().order_by('-created_at')
        regenerated_images = []
        for image_obj in generated_images:
            if not default_storage.exists(image_obj.image.name):
                # If the image file is missing, regenerate it from the saved img bytes
                image_data = image_obj.img_bytes
                if image_data:
                    img_name = f"v6_txt2img_N{image_obj.id}.png"
                    image_file = ContentFile(image_data, name=img_name)
                    image_obj.image = image_file
                    image_obj.save()
                    regenerated_images.append(image_obj)
                    print("regenerated..")
                else:
                    print("no image data bytes in object")
            else:
                regenerated_images.append(image_obj)

        paginator = Paginator(regenerated_images, 15)
        page_number = request.GET.get('page')
        page_object = paginator.get_page(page_number)

        return render(
            request, "img_api/img_gallery.html", {"page_obj": page_object}
        )
    except Exception as e:
        return HttpResponse(f"Error occurred: {str(e)}", status=500)


def detailView(request,id=None):
    try:
        obj = get_object_or_404(GeneratedImage,id=id)
        return render(request,'img_api/image.html',{"image_object":obj})
    except Exception as e:
        return HttpResponse(f"Error occurred: {str(e)}", status=500)

def generateView(request):
    context = {}
    try:
        if request.method == "POST":
            prompt = request.POST.get("text")
            number = int(request.POST.get("number"))
            style = request.POST.get('art_style')
            # print(style)#default is 3d
            if len(prompt) > 250:
                return HttpResponse("ValidText is required(max len 250).", status=400)

            # Generate images using API
            api_response = generate_images(prompt,number,style)
            # with open(r'.\media\response_api1080.json','+w') as f:
                # json.dump(api_response,f)
            # with open(r'.\media\response_api.json','r') as f:
            #     api_response = json.load(f)
            if api_response:
                
                user = request.user if request.user.is_authenticated else None
                        # image=ImageFile(open(image_path, 'rb')),
                generated_images_list = []
                for i, image in enumerate(api_response):
                    image_data = base64.b64decode(image["base64"])
                    img_name = f"v40_txt2img_{i}.png"
                    image_file = ContentFile(image_data, name=img_name)
                    generate_image = GeneratedImage(
                        user=user,
                        image=image_file,
                        text=prompt,
                        img_bytes = image_data,
                    )
                    generated_images_list.append(generate_image)

                GeneratedImage.objects.bulk_create(generated_images_list)
                context['new_image_objects'] = generated_images_list
                context['prompt']=prompt      
            else:
                return HttpResponse("Image generation failed.", status=500)

        if request.user.is_authenticated:
            generated_images_old = GeneratedImage.objects.filter(user=request.user)
            context["old_image_objects"] = generated_images_old

        print("n")
        return render(request, "img_api/img_get.html", context)
    
    except Exception as e:
        return HttpResponse(f"Error occurred: {str(e)}", status=500)


def generate_images(prompt,number,style):
    api_key = os.environ.get('API_TOI')
    api_host = 'https://api.stability.ai'
    engine_id = "stable-diffusion-v1-5"
    if api_key is None:
        raise Exception("Missing Stable API key.")
    try:

        response = requests.post(
            f"{api_host}/v1/generation/{engine_id}/text-to-image",
            headers={
                "Content-Type": "application/json",
                "Accept": "application/json",
                "Authorization": f"Bearer {api_key}",
            },
            json={
                "text_prompts": [{"text": prompt}],
                "cfg_scale": 7,
                "clip_guidance_preset": "FAST_BLUE",
                "style_preset": style,
                "height": 512,
                "width": 512,
                "samples": int(number),  # Number of images
                "steps": 30,
            },
        )
        if response.status_code != 200:
            error_message = "Non-200 response: " + str(response)
            return HttpResponse(error_message, status=response.status_code)
        
        data = response.json()
        return data.get("artifacts", [])
    
    except Exception as e:
        return None



templates/img_api/image.html
{% extends "includes/base.html" %}

{% block title %} AiImg Generator {% endblock %}

{% block main_content %}

<div class='main'>
    {% if image_object %}
    <div class="image-container">
        <div class="image-item">
            <p class="prompt-text">For Prompt: {{ g_img.text }}</p>
            <img src="{{ image_object.image.url }}" alt=" Image detail">
            <p class="created-at">Generated at: {{ g_img.created_at }}</p>

        </div>
    </div>
    {% else %}
    <p>No images available.</p>
    {% endif %}
</div>

{% endblock main_content %}

templates/img_api/img_gallery.html
{% extends "includes/base.html" %}

{% block title %} AiImg Generator {% endblock %}

{% block main_content %}

  <div class='main'>
    {% if page_obj %}
      <div class="image-container ">
        {% for image in page_obj %}
          <div class="image-item">
            <img src="{{ image.image.url }}" alt="Generated Image">
            <a href="{{ image.image.url }}">View Image</a>
          </div>
        {% endfor %}
        </div>
      {% else %}
        <p>No images available.</p>
      {% endif %}
  </div>

  <div class="pagination">
    {% if page_obj.has_previous %}
      <a href="?page=1">First</a>
      <a href="?page={{ page_obj.previous_page_number }}">Prev</a>
    {% endif %}

    <span class="current-page">{{ page_obj.number }}</span>

    {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}">Next</a>
      <a href="?page={{ page_obj.paginator.num_pages }}"> Last</a>
    {% endif %}
  </div>

{% endblock main_content %}

templates/img_api/img_get.html
{% extends "includes/base.html" %}

{% block title %}Img Generator{% endblock %}

{% block main_content %}

<div class="main">
    <form method="POST" class="form">
        {% csrf_token %}
        <input name="text" placeholder="Description about image..." required>
        <input name="number" type="number" step="1" min="2" max="10" placeholder="How many images? (2-10)" required>
        
    
        <div class='select-container' id='select-art'>
            <label for="art_style">Select Art Style:</label>
            <select id="art_style" name="art_style">
            <option value="3d-model">-style?(opt)-</option>
            <option value="3d-model">3D Model</option>
            <option value="anime">Anime</option>
            <option value="cinematic">Cinematic</option>
            <option value="digital-art">Digital Art</option>
            <option value="enhance">Enhance</option>
            <option value="fantasy-art">Fantasy Art</option>
            <option value="line-art">Line Art</option>
            <option value="modeling-compound">Modeling Compound</option>
            <option value="neon-punk">Neon Punk</option>
            <option value="photographic">Photographic</option>
            <option value="pixel-art">Pixel Art</option>
            </select>
            </div>
      
        <button type="submit" class="fm-btn">Generate 🖼️</button>
    </form>

    <div class="section2-out">
        {% if new_image_objects %}
        <span class="prompt-text">For Prompt: {{ prompt }}</span>
        <div class="image-container">
            {% for g_img in new_image_objects %}
            <div class="image-item">
                <img src="{{ g_img.image.url }}" alt="Generated new Image">
                <a href="{{ g_img.image.url }}">View Image</a>
            </div>
            {% endfor %}
        </div>
        {% else %}
        <h3 id="generating">Generating...</h3>
        {% endif %}
        {% comment %} {% if old_image_objects %}
        <h3 class="previous-text">Previous images...</h3>
        <div class="image-container">
                {% for g_img in old_image_objects %}
                <div class="image-item">
                    <img src="{{ g_img.image.url }}" alt="Old Image">
                    <a href="{{ g_img.image.url }}">View Image</a>
                </div>
            </div>
            {% endfor %}
        {% else %}
        <h3 id="login" >Login to save..</h3>
        {% endif %} {% endcomment %}

    </div>
</div>
<script>
    document.querySelector('.form').addEventListener('submit', function() {
        document.getElementById('generating').style.display = 'block';
    });
    
    {% comment %} {% if new_image_objects %}
    document.getElementById('login').style.display = 'block';
    {% else %}
    document.getElementById('login').style.display = 'none';
    document.getElementById('generating').style.display = 'none';
    {% endif %} {% endcomment %}
    
</script>

{% include 'includes/footer_p1.html' %}
{% endblock main_content %}


templates/includes/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'master.css' %}">
    
    <title> {% block title %} {% endblock %}</title>
</head>

<body>
    <nav >
    <div class='header'>
            <img src="{% static 'logo.png' %}" class='header-logo' />
        <h2>Image Generator</h2>
    </div>
    <div class="panel-link">
        <ul>
        <i class="arrow-right"></i>
        <a href={% url 'img_api:image-generate' %}>Generate</a>
        <span>/</span>
        <a href={% url 'img_api:image-gallery' %}>Gallery</a>
        </ul>   
    </div>
    </nav>
   
    
    {% block main_content %}
    
    {% endblock main_content %}

    <footer>

        {% block footer %}
        {% include 'includes/footer_p2.html' %} 
        {% endblock footer %} 
     
    </footer>
</body>

</html>

templates/includes/footer_p1.html
{% block footer_p1 %}
    <div class="f-panel-1">
        <h4>About AI Image Generation</h4>
        <p>
        This AI Image Generation is a web application that utilizes the
        Stability AI (Dreamstudio) APIs to generate realistic images based on text prompts.
        </p>
    </div>
{% endblock footer_p1 %}


templates/includes/footer_p2.html
{% block footer_p2 %}
    <div class="f-panel-2">
        <p>
            &copy; Developed by Ashish 
        </p>
    </div>
{% endblock footer_p2 %}

templates/includes/index.html
<!DOCTYPE html>

{% extends "includes/base.html" %}

{% block title %} Ai API's {% endblock %}


{% block main_content %}

<div class="container main">

    <h3 class='generating'>
        <a href="/images/"> CLick here </a> to Generate Ai Images...
    </h3>

</div>

{% endblock %}